// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceAuto.API.Data;

namespace ServiceAuto.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200610080258_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("ServiceAuto.API.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumarMasina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumarTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comenzi");
                });
#pragma warning restore 612, 618
        }
    }
}
